version: '3.7'
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn compo.wsgi:application --bind 0.0.0.0:8000
    volumes:
#      - static_volume:/app/web/staticfiles
#      - media_volume:/app/web/mediafiles
#      - ./static:/app/web/staticfiles
#      - ./media:/app/web/mediafiles
      - ./application:/app
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
#      - postgres_data:/var/lib/postgresql/data/
      - ./pgdata:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
#      - static_volume:/app/web/staticfiles
#      - media_volume:/app/web/mediafiles
      - ./static:/app/web/staticfiles
      - ./media:/app/web/mediafiles
    depends_on:
      - web

#volumes:
#  postgres_data:
#  static_volume:
#  media_volume:

